# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created: Thu Jun 11 18:18:55 2020
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 322)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 341, 321))
        self.stackedWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Pagina_principal = QtWidgets.QWidget()
        self.Pagina_principal.setObjectName("Pagina_principal")
        self.Premios = QtWidgets.QWidget(self.Pagina_principal)
        self.Premios.setGeometry(QtCore.QRect(20, 210, 311, 80))
        self.Premios.setObjectName("Premios")
        self.Asignaturas = QtWidgets.QWidget(self.Pagina_principal)
        self.Asignaturas.setEnabled(False)
        self.Asignaturas.setGeometry(QtCore.QRect(20, 40, 141, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Asignaturas.sizePolicy().hasHeightForWidth())
        self.Asignaturas.setSizePolicy(sizePolicy)
        self.Asignaturas.setMaximumSize(QtCore.QSize(573, 16777215))
        self.Asignaturas.setMouseTracking(False)
        self.Asignaturas.setObjectName("Asignaturas")
        self.mplvl = QtWidgets.QVBoxLayout(self.Asignaturas)
        self.mplvl.setContentsMargins(0, 0, 0, 0)
        self.mplvl.setObjectName("mplvl")
        self.Actitudes = QtWidgets.QWidget(self.Pagina_principal)
        self.Actitudes.setEnabled(False)
        self.Actitudes.setGeometry(QtCore.QRect(170, 40, 151, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Actitudes.sizePolicy().hasHeightForWidth())
        self.Actitudes.setSizePolicy(sizePolicy)
        self.Actitudes.setMaximumSize(QtCore.QSize(573, 16777215))
        self.Actitudes.setObjectName("Actitudes")
        self.mplvl_2 = QtWidgets.QVBoxLayout(self.Actitudes)
        self.mplvl_2.setContentsMargins(0, 0, 0, 0)
        self.mplvl_2.setObjectName("mplvl_2")
        self.down_arrow = QtWidgets.QLabel(self.Pagina_principal)
        self.down_arrow.setGeometry(QtCore.QRect(140, 300, 71, 21))
        self.down_arrow.setText("")
        self.down_arrow.setPixmap(QtGui.QPixmap("images/down-arrow.gif"))
        self.down_arrow.setScaledContents(True)
        self.down_arrow.setObjectName("down_arrow")
        self.Titulo = QtWidgets.QLabel(self.Pagina_principal)
        self.Titulo.setGeometry(QtCore.QRect(40, 10, 261, 21))
        self.Titulo.setFrameShape(QtWidgets.QFrame.Box)
        self.Titulo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Titulo.setLineWidth(0)
        self.Titulo.setText("")
        self.Titulo.setPixmap(QtGui.QPixmap("images/pi4logo-letters.png"))
        self.Titulo.setScaledContents(True)
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.stackedWidget.addWidget(self.Pagina_principal)
        self.Pagina_juegos = QtWidgets.QWidget()
        self.Pagina_juegos.setObjectName("Pagina_juegos")
        self.Titulo_2 = QtWidgets.QLabel(self.Pagina_juegos)
        self.Titulo_2.setGeometry(QtCore.QRect(10, 20, 161, 19))
        self.Titulo_2.setObjectName("Titulo_2")
        self.Lista_juegos = QtWidgets.QListWidget(self.Pagina_juegos)
        self.Lista_juegos.setGeometry(QtCore.QRect(10, 40, 321, 261))
        self.Lista_juegos.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Lista_juegos.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Lista_juegos.setAlternatingRowColors(False)
        self.Lista_juegos.setSelectionRectVisible(False)
        self.Lista_juegos.setObjectName("Lista_juegos")
        item = QtWidgets.QListWidgetItem()
        self.Lista_juegos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Lista_juegos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Lista_juegos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Lista_juegos.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Lista_juegos.addItem(item)
        self.up_arrow = QtWidgets.QLabel(self.Pagina_juegos)
        self.up_arrow.setGeometry(QtCore.QRect(140, 0, 71, 21))
        self.up_arrow.setText("")
        self.up_arrow.setPixmap(QtGui.QPixmap("images/up_arrow.gif"))
        self.up_arrow.setScaledContents(True)
        self.up_arrow.setObjectName("up_arrow")
        self.stackedWidget.addWidget(self.Pagina_juegos)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.Lista_juegos.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo_2.setText(_translate("MainWindow", "Games!"))
        self.Lista_juegos.setSortingEnabled(False)
        __sortingEnabled = self.Lista_juegos.isSortingEnabled()
        self.Lista_juegos.setSortingEnabled(False)
        item = self.Lista_juegos.item(0)
        item.setText(_translate("MainWindow", "Tetris"))
        item = self.Lista_juegos.item(1)
        item.setText(_translate("MainWindow", "2048"))
        item = self.Lista_juegos.item(2)
        item.setText(_translate("MainWindow", "Snake"))
        item = self.Lista_juegos.item(3)
        item.setText(_translate("MainWindow", "Arkanoid"))
        item = self.Lista_juegos.item(4)
        item.setText(_translate("MainWindow", "Asteroids"))
        self.Lista_juegos.setSortingEnabled(__sortingEnabled)


    def add_medal(self, name, x_translation):
        self.name = QtWidgets.QLabel(self.Premios)
        self.name.setEnabled(True)
        self.name.setGeometry(QtCore.QRect(x_translation, 10, 51, 61))
        self.name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name.setText("")
        self.name.setPixmap(QtGui.QPixmap("images/medal.png"))
        self.name.setScaledContents(True)
        self.name.setObjectName(name)

    def add_trophy(self, name, x_translation):
        self.name = QtWidgets.QLabel(self.Premios)
        self.name.setEnabled(True)
        self.name.setGeometry(QtCore.QRect(x_translation, 10, 51, 61))
        self.name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name.setText("")
        self.name.setPixmap(QtGui.QPixmap("images/trophy.png"))
        self.name.setScaledContents(True)
        self.name.setObjectName(name)